[features]
seeds = false
skip-lint = false

[programs.localnet]
thyxel_hook = "THYXhook111111111111111111111111111111111"

[programs.devnet]
thyxel_hook = "THYXhook111111111111111111111111111111111"

[programs.mainnet-beta]
thyxel_hook = "THYXhook111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "yarn run ts-node scripts/deploy.ts"
create-token = "yarn run ts-node scripts/create-token.ts"
